apiVersion: v1
kind: Service
metadata:
    name: "aksdemogilad-3cb1"
    labels:
        app: "aksdemogilad-3cb1"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksdemogilad-3cb1"